USE [master]
GO

/****** Object:  Database [Premiership]    Script Date: 2021. 10. 06. 20:06:51 ******/
CREATE DATABASE [Premiership]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Premiership', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Premiership.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Premiership_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Premiership_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Premiership].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Premiership] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Premiership] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Premiership] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Premiership] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Premiership] SET ARITHABORT OFF 
GO

ALTER DATABASE [Premiership] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Premiership] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Premiership] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Premiership] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Premiership] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Premiership] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Premiership] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Premiership] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Premiership] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Premiership] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Premiership] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Premiership] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Premiership] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Premiership] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Premiership] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Premiership] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Premiership] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Premiership] SET RECOVERY FULL 
GO

ALTER DATABASE [Premiership] SET  MULTI_USER 
GO

ALTER DATABASE [Premiership] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Premiership] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Premiership] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Premiership] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Premiership] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Premiership] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Premiership] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Premiership] SET  READ_WRITE 
GO

