SELECT TOP 1 PLAYER.PLAYER_NAME, COUNT(GOAL.GOAL_ID) AS [SCORED_GOALS]
FROM PLAYER
JOIN GOAL
ON PLAYER.PLAYER_ID = GOAL.PLAYER_ID
JOIN NATION 
ON NATION.NATION_ID = PLAYER.NATION_ID
WHERE NATION.NATION_NAME = 'Spain'
GROUP BY NATION.NATION_ID, PLAYER.PLAYER_NAME
ORDER BY COUNT(GOAL.GOAL_ID) DESC