SELECT TOP 1 PLAYER_NAME, COUNT(GOAL.GOAL_ID) AS [TOP GOAL SCORER FROM 1ST TEAM]
FROM PLAYER
JOIN GOAL
ON PLAYER.PLAYER_ID = GOAL.PLAYER_ID
JOIN TROPHY
ON PLAYER.TEAM_ID = TROPHY.TEAM_ID
GROUP BY PLAYER.PLAYER_NAME
ORDER BY COUNT(GOAL.GOAL_ID) DESC
