SELECT TOP 1 MANAGER_NAME, DATEDIFF(DAY, START_DATE, END_DATE) AS [Number of days as a manager] 
FROM MANAGER
JOIN TEAM_MANAGER 
ON MANAGER.MANAGER_ID = TEAM_MANAGER.MANAGER_ID
WHERE END_DATE IS NOT NULL
ORDER BY [Number of days as a manager]  ASC