SELECT TOP 1 GOAL.MATCH_ID
FROM GOAL
JOIN PLAYER
ON PLAYER.PLAYER_ID = GOAL.PLAYER_ID
JOIN NATION 
ON NATION.NATION_ID = PLAYER.NATION_ID
WHERE NATION.NATION_NAME = 'England'
GROUP BY GOAL.MATCH_ID
ORDER BY COUNT(PLAYER.PLAYER_ID) DESC