SELECT TOP 1 TEAM.TEAM_NAME, SUM(HOME_SCORE) AS [SCORED GOALS AT HOME]
FROM TEAM
JOIN MATCH
ON TEAM.TEAM_ID = MATCH.HOME_TEAM_ID
WHERE TEAM.TEAM_ID = MATCH.HOME_TEAM_ID 
GROUP BY TEAM.TEAM_NAME
ORDER BY SUM(HOME_SCORE) ASC