SELECT COUNT (PLAYER.PLAYER_ID), TOP 1 SUM(HOME_SCORE), HOME_TEAM_ID
FROM MATCH
GROUP BY HOME_TEAM_ID
ORDER BY SUM(HOME_SCORE) DESC

/*
SELECT COUNT(PLAYER.PLAYER_ID)
FROM PLAYER
JOIN NATION
ON PLAYER.NATION_ID = NATION.NATION_ID
WHERE PLAYER.TEAM_ID = 9 AND NATION.NATION_NAME = 'England'
*/