SELECT TOP 1 COUNT(PLAYER.NATION_ID) AS [TOP NUMBER OF PLAYERS FROM A COUNTRY]
FROM PLAYER
JOIN NATION
ON PLAYER.NATION_ID = NATION.NATION_ID
GROUP BY PLAYER.NATION_ID, NATION.NATION_NAME
ORDER BY [TOP NUMBER OF PLAYERS FROM A COUNTRY] DESC