SELECT TOP 1 MANAGER.MANAGER_NAME
FROM MANAGER
JOIN TEAM_MANAGER
ON MANAGER.MANAGER_ID = TEAM_MANAGER.MANAGER_ID
JOIN MATCH
ON TEAM_MANAGER.TEAM_ID = MATCH.HOME_TEAM_ID
GROUP BY MANAGER.MANAGER_NAME
ORDER BY MAX(MATCH.HOME_SCORE) DESC