/*SELECT COUNT (PLAYER.PLAYER_ID), TOP 1 SUM(HOME_SCORE), HOME_TEAM_ID
FROM MATCH
GROUP BY HOME_TEAM_ID
ORDER BY SUM(HOME_SCORE) DESC
*/

SELECT TOP 1 COUNT(PLAYER.PLAYER_ID)
FROM PLAYER
JOIN NATION
ON PLAYER.NATION_ID = NATION.NATION_ID
JOIN MATCH
ON PLAYER.TEAM_ID = MATCH.HOME_TEAM_ID
WHERE NATION.NATION_NAME = 'England'
GROUP BY PLAYER.PLAYER_ID
ORDER BY MAX(MATCH.HOME_SCORE) DESC